src/app/app-routing.module.ts
src/app/pages/auth/sign-in/sign-in.component.css
src/app/pages/auth/sign-in/sign-in.component.html
src/app/pages/auth/sign-in/sign-in.component.ts
src/app/pages/auth/sign-up/sign-up.component.css
src/app/pages/auth/sign-up/sign-up.component.html
src/app/pages/auth/sign-up/sign-up.component.ts

feat: signIn/signUp
Refs: FF1-4

FF1-4-FE-signin/signup

---

src/app/pages/client/cart-page/cart-page.component.html

feat: giao diện giỏ hàng
Refs: FF1-6

FF1-6-FE-cart

---

BE/src/app.js
BE/src/models/category.js
BE/src/models/comment.js
BE/src/models/order.js
BE/src/models/product.js
BE/src/models/user.js

feat: BE up model and app.js

---

BE/src/app.js
BE/src/controller/auth.js
BE/src/router/auth.js
BE/src/validate/login.js
BE/src/validate/register.js

feat: up code be auth

---

BE/.env
BE/src/app.js
BE/src/component/formEmail.js
BE/src/component/function.js
BE/src/controller/forgot.js
BE/src/middleware/sendMail.js
BE/src/router/forgot.js

feat: up BE forgot-pass

---

BE/src/app.js
src/app/services/products/products.service.spec.ts
src/app/services/products/products.service.ts

feat: products Services 
ref: FF1-21

FF1-21-FE-Services-Product

---

BE/src/middleware/checkPermission.js

feat: up BE check permission

---

BE/src/app.js
BE/src/controller/category.js
BE/src/router/category.js

feat: up category

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/pages/client/contact-page/contact-page.component.css
src/app/pages/client/contact-page/contact-page.component.html
src/app/pages/client/contact-page/contact-page.component.spec.ts
src/app/pages/client/contact-page/contact-page.component.ts

feat: up fe contact

---

BE/package-lock.json
BE/package.json
BE/src/app.js
BE/src/controller/auth.js
BE/src/controller/forgot.js
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/pages/auth/forgot-password/forgot-password.component.html
src/app/pages/auth/forgot-password/forgot-password.component.spec.ts
src/app/pages/auth/forgot-password/forgot-password.component.ts
src/app/pages/auth/reset-password/reset-password.component.html
src/app/pages/auth/reset-password/reset-password.component.spec.ts
src/app/pages/auth/reset-password/reset-password.component.ts
src/app/services/auth/auth.service.ts

feat: quên mật khẩu
ref: FF1-24

FF1-24-FE-Services-Forgot-Password

---

BE/src/app.js
BE/src/controller/order.js
BE/src/router/order.js
BE/src/validate/order.js

feat: up BE order

---

src/app/services/category/category.service.spec.ts
src/app/services/category/category.service.ts

feat: up service category

---

src/app/pages/client/product-detail/product-detail.component.html
src/app/pages/client/product-detail/product-detail.component.ts
src/app/services/products/products.service.ts

feat: services comment

---

BE/src/app.js
BE/src/component/formEmail.js
BE/src/component/function.js
BE/src/controller/auth.js
BE/src/controller/category.js
BE/src/controller/comment.js
BE/src/controller/contact.js
BE/src/controller/forgot.js
BE/src/controller/order.js
BE/src/controller/product.js
BE/src/middleware/checkPermission.js
BE/src/middleware/sendMail.js
BE/src/models/category.js
BE/src/models/comment.js
BE/src/models/contact.js
BE/src/models/order.js
BE/src/router/category.js
BE/src/router/contact.js
BE/src/router/forgot.js
BE/src/router/order.js
BE/src/router/product.js
BE/src/validate/category.js
BE/src/validate/component/function.js
BE/src/validate/contact.js
BE/src/validate/login.js
BE/src/validate/order.js
BE/src/validate/product.js
BE/src/validate/register.js

feat: up BE contact

---

src/app/pages/auth/forgot-password/forgot-password.component.html
src/app/pages/auth/reset-password/reset-password.component.html
src/app/pages/client/contact-page/contact-page.component.html
src/app/pages/client/contact-page/contact-page.component.ts
src/app/pages/client/product-detail/product-detail.component.html
src/app/services/contacts/contact.service.spec.ts
src/app/services/contacts/contact.service.ts

feat: up fe services contact

---

src/app/app.component.html
src/app/app.module.ts
src/app/layouts/admin/base-admin/base-admin.component.html
src/app/layouts/admin/footer-admin/footer-admin.component.html
src/app/layouts/admin/footer-admin/footer-admin.component.spec.ts
src/app/layouts/admin/footer-admin/footer-admin.component.ts
src/app/layouts/admin/header-admin/header-admin.component.css
src/app/layouts/admin/header-admin/header-admin.component.html
src/app/layouts/admin/header-admin/header-admin.component.spec.ts
src/app/layouts/admin/header-admin/header-admin.component.ts
src/app/layouts/admin/nav-admin/nav-admin.component.html
src/app/layouts/admin/nav-admin/nav-admin.component.spec.ts
src/app/layouts/admin/nav-admin/nav-admin.component.ts
src/app/pages/admin/admin-category/admin-category.component.css
src/app/pages/admin/admin-category/admin-category.component.html
src/app/pages/admin/admin-dash-board/admin-dash-board.component.css
src/app/pages/admin/admin-dash-board/admin-dash-board.component.html
src/app/pages/admin/admin-order/admin-order.component.css
src/app/pages/admin/admin-order/admin-order.component.html
src/app/pages/admin/admin-product/admin-product.component.css
src/app/pages/admin/admin-product/admin-product.component.html
src/app/pages/admin/admin-user/admin-user.component.css
src/app/pages/admin/admin-user/admin-user.component.html
src/index.html

feat: up fe admin

---

BE/src/controller/auth.js
BE/src/models/user.js
BE/src/router/auth.js
src/app/pages/admin/admin-user/admin-user.component.css
src/app/pages/admin/admin-user/admin-user.component.html
src/app/pages/admin/admin-user/admin-user.component.ts
src/app/services/auth/auth.service.ts

feat: up FE services Admin user

---

BE/src/controller/contact.js
BE/src/router/contact.js
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/layouts/admin/nav-admin/nav-admin.component.html
src/app/pages/admin/admin-contact/admin-contact.component.html
src/app/pages/admin/admin-contact/admin-contact.component.spec.ts
src/app/pages/admin/admin-contact/admin-contact.component.ts
src/app/pages/admin/admin-user/admin-user.component.ts
src/app/services/contacts/contact.service.ts

feat: up admin contact

---

src/app/pages/auth/sign-in/sign-in.component.ts
src/app/pages/client/pay-page/pay-page.component.html
src/app/pages/client/pay-page/pay-page.component.ts
src/app/pages/client/product-detail/product-detail.component.ts
src/app/services/order/order.service.spec.ts
src/app/services/order/order.service.ts

FF1-22-FE-Services-Order

---

BE/.env
src/app/pages/admin/admin-category/admin-category.component.html
src/app/pages/admin/admin-category/admin-category.component.ts
src/app/services/category/category.service.ts

feat: up admin category

---

BE/src/controller/verify.js

feat: up verify email be

---

BE/src/controller/payment.js
BE/src/models/payment.js

feat: up be payment

---

BE/src/controller/auth.js
BE/src/router/auth.js
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/layouts/client/header-client/header-client.component.html
src/app/pages/auth/infomation/infomation.component.html
src/app/pages/auth/infomation/infomation.component.spec.ts
src/app/pages/auth/infomation/infomation.component.ts
src/app/pages/auth/information-update/information-update.component.html
src/app/pages/auth/information-update/information-update.component.spec.ts
src/app/pages/auth/information-update/information-update.component.ts
src/app/services/auth/auth.service.ts

feat: thông tin khách hàng
ref: FF1-41

FF1-41-FE-Personal-Information

---

BE/src/controller/product.js
BE/src/router/product.js
src/app/app-routing.module.ts
src/app/layouts/client/header-client/header-client.component.html
src/app/layouts/client/header-client/header-client.component.ts
src/app/pages/client/search-page/search-page.component.css
src/app/pages/client/search-page/search-page.component.html
src/app/pages/client/search-page/search-page.component.ts
src/app/services/products/products.service.ts

feat: up be search

---

src/app/pages/auth/information/information.component.html
src/app/pages/auth/information/information.component.ts

feat: up be change password
